### ISSUE TITLE
'add_select' functionalities

### ISSUE THREAD

**Issue by driesverheyen** [crazycapivara/openlayers#16]
First of all thank for this great package

When I choose add_select(condition = "pointerMove", display_properties=TRUE), it doesn't show feature properties on hover. Here a code example:

---
title: "Openlayers Test"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(openlayers)
library(knitr)
library(sf)

nc<-st_read(system.file("shape/nc.shp", package="sf"))
```

Map
-----------------------------------------------------------------------

### American States

```{r, echo=FALSE}
ol()%>%
  add_features(data = nc, popup = nc$NAME)%>%
  add_select(condition="pointerMove",display_properties = TRUE)%>%
  add_scale_line()%>%
  add_mouse_position()
```

How can I display feature properties on hover, and can this have the same functionality as 'popup = nc$NAME', meaning that you can choose which feature properties will be shown on hover?

Also, is it possible to define a style of the selected feature? Now it is standard a thicker blue line. Would be nice to give add_select also a style object.

Thanks,

Dries Verheyen

**Comment by driesverheyen** [comment]
When running the code in the Rstudio Viewer the feature properties are displayed underneath the map widget. Because they are full screen in 'flexdashboard' you cannot see them anymore. So it is working but not in flexdashboard.

Still displaying feature data on hover and styling the select would be nice to have.

**Comment by crazycapivara** [comment]
Hi,

yes you are right, the problem is that there is no fixed height for the container display the properties.

Your request passing custom styles for selected features is something I also wanted to implement.

I created issues for both requests.

**Comment by crazycapivara** [comment]
see #18, #17

**Comment by driesverheyen** [comment]
OK, thanks!

**Comment by crazycapivara** [comment]
Please install latest version and test it. Properties are now displayed as overlay (fixes #18).

**Comment by driesverheyen** [comment]
Ok thanks, this works in flex_dashboard. Will there be an enhancement where you can select which properties to show? And can they also been shown as tooltip at the mouseposition?

**Comment by crazycapivara** [comment]
I will take a look at it.
