### ISSUE TITLE
Add popups

### ISSUE THREAD

**Issue by crazycapivara** [crazycapivara/openlayers#4]
Add support for binding popups to features. Therefore, add `popup` parameter to functions adding features.

**Comment by crazycapivara** [comment]
Added in v0.4.3

**Comment by fliermanrw** [comment]
Could you elaborate on how the properties of the clicked element (e.g. geoJson layer) can be shown on popup?

**Comment by crazycapivara** [comment]
```r
library("sf")

nc <- st_read(system.file("gpkg/nc.gpkg", package = "sf"),
             quiet = TRUE)

ol() %>%
  add_stamen_tiles("watercolor") %>%
  add_features(
    data = nc,
    style = fill_style("yellow") + stroke_style("blue", 1),
    popup = nc$AREA  
  )
```

**Comment by crazycapivara** [comment]
see also [examples/use_popups.R](https://github.com/crazycapivara/openlayers/blob/develop/inst/examples/use_popups.R)
